/** @type {import('tailwindcss').Config} */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#6ffbbe",
        "tertiary-container": "#535ca9",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-container": "#e0dcff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-dim": "#d4dbdb",
        "surface": "#f4fbfa",
        "background": "#f4fbfa",
        "on-primary-fixed-variant": "#3e31ac",
        "outline": "#787585",
        "on-primary-fixed": "#130067",
        "surface-container": "#e8efef",
        "primary-container": "#5b51ca",
        "on-background": "#161d1d",
        "inverse-on-surface": "#ebf2f2",
        "on-secondary-container": "#00714d",
        "outline-variant": "#c8c4d5",
        "surface-tint": "#574cc5",
        "surface-container-highest": "#dde4e3",
        "on-secondary-fixed-variant": "#005236",
        "error-container": "#ffdad6",
        "inverse-surface": "#2b3232",
        "secondary": "#006c49",
        "tertiary-fixed": "#dfe0ff",
        "inverse-primary": "#c5c0ff",
        "primary-fixed": "#e3dfff",
        "tertiary-fixed-dim": "#bdc2ff",
        "on-primary": "#ffffff",
        "surface-bright": "#f4fbfa",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#c5c0ff",
        "tertiary": "#3b4390",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-container": "#dbddff",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#002113",
        "on-tertiary-fixed": "#030c60",
        "on-surface": "#161d1d",
        "primary": "#4236b1",
        "on-error-container": "#93000a",
        "surface-container-low": "#eef5f4",
        "on-surface-variant": "#474553",
        "secondary-container": "#6cf8bb",
        "on-tertiary-fixed-variant": "#363f8b",
        "surface-container-high": "#e2eae9",
        "surface-variant": "#dde4e3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "margin-desktop": "40px",
        gutter: "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.7", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        caption: ["12px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.7", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.5", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}

